# .github/workflows/ci.yml
name: Node CI
on: [push]

env:
  NODE_VERSION: 18

jobs:
  linting:
    name: CI Steps
    runs-on: ubuntu-latest
    steps:
      - name: install NodeJS
        uses: actions/setup-node@v2
        with:
          node-version: ${{ env.NODE_VERSION }}
      - name: Code Checkout
        uses: actions/checkout@v2
      - name: npm install
        run: |
            npm install
      - name: npm run build
        run: |
            npm run build --if-present
            npm run lint
      - name: npm test
        run: |
          npm run test:ci
